services:
  pebble-loop:
    container_name: pebble-loop
    image: pebble-loop:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["loop", "--config", "/app/config-Midnight-S1.yaml", "--trigger-timeout", "5"]
    restart: unless-stopped
    env_file:
      - .env
